# Generated by Django 4.0.2 on 2022-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactnumber',
            name='contact_for',
        ),
        migrations.RemoveField(
            model_name='contactnumber',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='emergency_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Center Phone Number'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='help_desk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help Desk Phone Number'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='station_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Station Phone Number'),
        ),
    ]
