# Generated by Django 4.0.2 on 2022-02-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_train_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='To+', to='app.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='From+', to='app.station'),
        ),
    ]
