# Generated by Django 4.0.2 on 2022-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_classtype_alter_train_destination_alter_train_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Train Name'),
        ),
    ]
