# Generated by Django 4.0.2 on 2022-02-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_train_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Train Name'),
        ),
    ]
