# Generated by Django 4.0.2 on 2022-03-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_ticket_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
    ]
