# Generated by Django 4.0.2 on 2022-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
