# Generated by Django 4.0.2 on 2022-03-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_booking_sub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sub_date',
        ),
    ]
