# Generated by Django 4.0.2 on 2022-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_booking_sub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
